// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace My_MVCApp.Models;

public partial class Registration
{
    [Required(ErrorMessage ="Please enter username")]
    public string Uname { get; set; }
    [Required(ErrorMessage ="Pls Enter password")]
    public string Password { get; set; }

    public bool? Gender { get; set; }

    public DateTime? Dob { get; set; }
    [EmailAddress(ErrorMessage ="pls enter valid email")]
    public string Email { get; set; }
    [StringLength(10,ErrorMessage ="not a 10 digit long")]
    [RegularExpression("[0-9]+",ErrorMessage ="Only Numbers are allowed")]
    public string Phone { get; set; }
}